import numpy as np
import sys
import torch
sys.path.append('../../deepextractor/')
from models.models import UNET2D # DeepExtractor is based on the U-Net architecture
import pickle
import sklearn
import matplotlib.pyplot as plt
import bilby
import argparse
import os




def parse_args():
    parser = argparse.ArgumentParser(description="Reconstruct SNR using DeepExtractor")
    parser.add_argument("--data", type = str, help = "Location of the frame files (npz file) generated by generate_frames.py script")
    parser.add_argument("--model", type = str, default = "../../deepextractor/checkpoints_1024/UNET2D_glitch_target_checkpoints/checkpoint_best_bilby_noise_transfer_learn.pth.tar")
    parser.add_argument("--outdir", type = str, default="deleteme")
    parser.add_argument("--label", type = str, default="deleteme")

    return parser.parse_args()

def compute_snr(reconstruced_signal, data, duration = 2, sampling_frequency = 4096):
    do_fft = False
    if do_fft:
        signal_fft, _ = bilby.core.utils.nfft(reconstruced_signal, sampling_frequency)
        data_fft, _ = bilby.core.utils.nfft(data, sampling_frequency)

        sigma_squared = 4/duration * np.real(np.sum(data_fft * np.conj(signal_fft)))

    else:
        sigma_squared = np.sum(reconstruced_signal*data)
    return np.sqrt(abs(sigma_squared)) 


def process_segments(data_array, model, scaler, device, segment_size=8192):
    """
    Divide data into segments, reconstruct signal for each, and return SNR values.

    Args:
        data_array: Input numpy array (e.g., data['ET1'])
        model: Fine-tuned model for noise prediction
        scaler: Scaler for normalizing/denormalizing the data
        device: Device to run the model on ('cuda' or 'cpu')
        segment_size: Size of each segment (default: 8192)

    Returns:
        snr_values: List of SNR values for each segment
    """
    n_samples = len(data_array)
    n_segments = n_samples // segment_size

    snr_values = []

    for i in range(n_segments):
        start_idx = i * segment_size
        end_idx = start_idx + segment_size
        segment = data_array[start_idx:end_idx]

        reconstructed = reconstruct_signal(segment, model, scaler, device)
        snr = compute_snr(reconstructed, segment)
        snr_values.append(snr)

    return np.array(snr_values)


def reconstruct_signal(input_series, model, scaler, device):
    """
    Reconstruct a glitch signal by subtracting predicted noise from the input.

    Args:
        input_series: Input time series (numpy array)
        model: Fine-tuned model for noise prediction
        scaler: Scaler for normalizing/denormalizing the data
        device: Device to run the model on ('cuda' or 'cpu')

    Returns:
        g_hat: Reconstructed glitch signal (numpy array)
    """
    # STFT parameters
    n_fft = 256
    win_length = n_fft // 2
    hop_length = win_length // 2
    window = torch.hann_window(win_length)

    # Scale the input
    input_scaled = scaler.transform(input_series.reshape(-1, 1)).reshape(input_series.shape)

    # Convert to tensor and compute STFT
    signal_tensor = torch.tensor(input_scaled, dtype=torch.float32)
    stft_result = torch.stft(
        signal_tensor,
        n_fft=n_fft,
        hop_length=hop_length,
        win_length=win_length,
        window=window,
        return_complex=True
    )

    # Extract magnitude and phase
    magnitude = torch.abs(stft_result)
    phase = torch.angle(stft_result)

    # Stack and prepare for model
    stft_mag_phase = torch.stack([magnitude, phase], dim=0)
    stft_mag_phase = stft_mag_phase.unsqueeze(0)
    h_stft = stft_mag_phase.float().to(device)

    # Model prediction
    with torch.no_grad():
        n_hat_stft = model(h_stft)

    n_hat_stft = n_hat_stft.cpu()

    # Separate magnitude and phase from prediction
    magnitude_pred = n_hat_stft[:, 0, :, :]
    phase_pred = n_hat_stft[:, 1, :, :]

    # Convert back to complex STFT
    real_part = magnitude_pred * torch.cos(phase_pred)
    imag_part = magnitude_pred * torch.sin(phase_pred)
    stft_complex = torch.complex(real_part, imag_part)

    # Perform iSTFT to get time series
    n_hat_scaled = torch.istft(
        stft_complex,
        n_fft=n_fft,
        hop_length=hop_length,
        win_length=win_length,
        window=window,
    )
    n_hat_scaled = n_hat_scaled.numpy().squeeze()

    # Scale back the inverse transformed data
    n_hat = scaler.inverse_transform(
        n_hat_scaled.reshape(-1, n_hat_scaled.shape[-1])
    ).reshape(n_hat_scaled.shape)

    # Reconstruct the glitch by subtracting the predicted noise
    s_hat = input_series - n_hat

    return s_hat





def make_plots(args, dex_snr):
    segment_index = np.arange(len(dex_snr['ET1']))

    ############################################################
    fig, axes = plt.subplots(2, 1, sharex = True, sharey = True)
    ax = axes[0]

    ax.scatter(segment_index, dex_snr['ET2'])

    ax.set_xlabel("Seconds")

    ax = axes[1]
    ax.scatter(segment_index, dex_snr['null_stream'], color = 'blue', label = 'null stream statistic')

    ax.legend()

    ax.set_xlabel("Seconds")
    fig.savefig(f"{args.outdir}/{args.label}_snr_timeseries.pdf")
    ############################################################


    fig, ax = plt.subplots(1, 1)
    ax.hist(dex_snr['ET2'], cumulative=0, histtype='step', density = 0)
    ax.set_xlabel("SNR")
    fig.savefig(f"{args.outdir}/{args.label}/snr_foreground_histogram.pdf")


def main():
    args = parse_args()
    if not os.path.isdir(args.outdir):
        os.mkdir(args.outdir)


    model_fine_tuned = UNET2D(in_channels=2, out_channels=2)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model_fine_tuned.to(device)

    data = np.load(args.data)

    weights = torch.load(args.model, map_location=device, weights_only=True)
    model_fine_tuned.load_state_dict(weights['state_dict'])
    model_fine_tuned.eval()

    scaler = pickle.load(open("../../deepextractor/data/scaler_bilby.pkl", 'rb'))

    detectors = ['ET1', 'ET2', 'ET3']

    dex_snr = {}
    for i, det in enumerate(detectors):
        input_timeseries = np.asarray(data[det])
        dex_snr[det] = process_segments(input_timeseries, model_fine_tuned, scaler, device)

    dex_snr['null_stream'] = np.sqrt(3)*(process_segments(np.asarray(data['null_stream']), model_fine_tuned, scaler, device))

    make_plots(args, dex_snr)


if __name__ == "__main__":
    main()