import numpy as np
import sys
import torch
sys.path.append('../../deepextractor/')
from models.models import UNET2D # DeepExtractor is based on the U-Net architecture
import pickle
import sklearn
import matplotlib.pyplot as plt
import bilby
import argparse
import os
import logging
from tqdm import tqdm
import scienceplots
from pycbc.types import TimeSeries
from pycbc.filter.matchedfilter import match
plt.style.use(['science'])

logger = logging.getLogger("reconstruct")


def setup_logger(outdir, label):
    logger.setLevel(logging.INFO)
    fh = logging.FileHandler(f"{outdir}/{label}.log")
    fh.setFormatter(logging.Formatter("%(asctime)s - %(levelname)s - %(message)s"))
    logger.addHandler(fh)



def parse_args():
    parser = argparse.ArgumentParser(description="Reconstruct SNR using DeepExtractor")
    parser.add_argument("--data", type = str, help = "Location of the frame files (npz file) generated by generate_frames.py script")
    parser.add_argument("--model", type = str, default = "../../deepextractor/checkpoints_1024/UNET2D_glitch_target_checkpoints/checkpoint_best_bilby_noise_transfer_learn.pth.tar")
    parser.add_argument("--outdir", type = str, default="deleteme")
    parser.add_argument("--label", type = str, default="deleteme")
    parser.add_argument("--sampling-frequency", type = float, default = 4096)
    parser.add_argument("--minimum-frequency", type = float, default=20.)
    parser.add_argument("--delta-t", type = float, default=2, help = "Sliding duration for the DE window")

    return parser.parse_args()

def compute_snr(reconstruced_signal, data, duration = 2, sampling_frequency = 4096):
    do_fft = False
    if do_fft:
        signal_fft, _ = bilby.core.utils.nfft(reconstruced_signal, sampling_frequency)
        data_fft, _ = bilby.core.utils.nfft(data, sampling_frequency)

        sigma_squared = 4/duration * np.real(np.sum(data_fft * np.conj(signal_fft)))

    else:
        sigma_squared = np.sum(reconstruced_signal*data)
    return np.sqrt(abs(sigma_squared)) 




def process_segments(data_array, model, scaler, delta_t, sampling_frequency, device, segment_size=8192):
    """
    Divide data into segments, reconstruct signal for each, and return SNR values.

    Args:
        data_array: Input numpy array (e.g., data['ET1'])
        model: Fine-tuned model for noise prediction
        scaler: Scaler for normalizing/denormalizing the data
        device: Device to run the model on ('cuda' or 'cpu')
        segment_size: Size of each segment (default: 8192)

    Returns:
        snr_values: List of SNR values for each segment
    """
    n_samples = len(data_array)
    #n_segments = n_samples // segment_size

    snr_values = []
    start_idx=0

    end_idx=8192

    bins = np.arange(0, n_samples - segment_size + 1, int(delta_t*sampling_frequency), dtype=int)
    time_stamps = bins[:-1] / sampling_frequency
    for ii in tqdm(range(len(bins)-1)):
        start_idx = bins[ii]
        end_idx = bins[ii+1]
        segment = data_array[start_idx:end_idx]
        reconstructed = reconstruct_signal(segment, model, scaler, device)
        snr = compute_snr(reconstructed, segment)
        snr_values.append(snr)


    

        

    return np.array(snr_values), time_stamps


def joint_processing(data_array_1, data_array_2, model, scaler, delta_t, sampling_frequency, device, minimum_frequency, segment_size=8192):
    n_samples = len(data_array_1)
    bins = np.arange(0, n_samples - segment_size + 1, int(delta_t * sampling_frequency), dtype=int)
    time_stamps = bins[:-1]/sampling_frequency

    snr_values_1, snr_values_2, match_values = [], [], []
    for ii in tqdm(range(len(bins) - 1)):
        seg_1, seg_2 = data_array_1[bins[ii]:bins[ii+1]], data_array_2[bins[ii]:bins[ii+1]]
        rec_1, rec_2 = reconstruct_signal(seg_1, model, scaler, device), reconstruct_signal(seg_2, model, scaler, device)

        snr_values_1.append(compute_snr(rec_1, seg_1))
        snr_values_2.append(compute_snr(rec_2, seg_2))
        match_values.append(compute_overlap(rec_1, rec_2, sampling_frequency, minimum_frequency))

    return np.array(snr_values_1), np.array(snr_values_2), np.array(match_values), time_stamps

def reconstruct_signal(input_series, model, scaler, device):
    """
    Reconstruct a glitch signal by subtracting predicted noise from the input.

    Args:
        input_series: Input time series (numpy array)
        model: Fine-tuned model for noise prediction
        scaler: Scaler for normalizing/denormalizing the data
        device: Device to run the model on ('cuda' or 'cpu')

    Returns:
        g_hat: Reconstructed glitch signal (numpy array)
    """
    # STFT parameters
    n_fft = 256
    win_length = n_fft // 2
    hop_length = win_length // 2
    window = torch.hann_window(win_length)

    # Scale the input
    input_scaled = scaler.transform(input_series.reshape(-1, 1)).reshape(input_series.shape)

    # Convert to tensor and compute STFT
    signal_tensor = torch.tensor(input_scaled, dtype=torch.float32)
    stft_result = torch.stft(
        signal_tensor,
        n_fft=n_fft,
        hop_length=hop_length,
        win_length=win_length,
        window=window,
        return_complex=True
    )

    # Extract magnitude and phase
    magnitude = torch.abs(stft_result)
    phase = torch.angle(stft_result)

    # Stack and prepare for model
    stft_mag_phase = torch.stack([magnitude, phase], dim=0)
    stft_mag_phase = stft_mag_phase.unsqueeze(0)
    h_stft = stft_mag_phase.float().to(device)

    # Model prediction
    with torch.no_grad():
        n_hat_stft = model(h_stft)

    n_hat_stft = n_hat_stft.cpu()

    # Separate magnitude and phase from prediction
    magnitude_pred = n_hat_stft[:, 0, :, :]
    phase_pred = n_hat_stft[:, 1, :, :]

    # Convert back to complex STFT
    real_part = magnitude_pred * torch.cos(phase_pred)
    imag_part = magnitude_pred * torch.sin(phase_pred)
    stft_complex = torch.complex(real_part, imag_part)

    # Perform iSTFT to get time series
    n_hat_scaled = torch.istft(
        stft_complex,
        n_fft=n_fft,
        hop_length=hop_length,
        win_length=win_length,
        window=window,
    )
    n_hat_scaled = n_hat_scaled.numpy().squeeze()

    # Scale back the inverse transformed data
    n_hat = scaler.inverse_transform(
        n_hat_scaled.reshape(-1, n_hat_scaled.shape[-1])
    ).reshape(n_hat_scaled.shape)

    # Reconstruct the glitch by subtracting the predicted noise
    s_hat = input_series - n_hat

    return s_hat


def compute_overlap(ts1, ts2, sampling_frequency, minimum_frequency):
    ts1 = TimeSeries(ts1, delta_t=1/sampling_frequency, epoch=0.)
    ts2 = TimeSeries(ts2, delta_t=1/sampling_frequency, epoch=0)
    #PSD?
    overlap, _ = match(ts1, ts2, low_frequency_cutoff=minimum_frequency, high_frequency_cutoff=sampling_frequency*0.5)
    return overlap



def main():
    """
    This function filters the data generated by generate_frames.py script. 
    It filters the data using the DE model.
    It saves the SNR estimated by the DE model in the form of numpy arrays. 

    """
    args = parse_args()
    if not os.path.isdir(args.outdir):
        os.mkdir(args.outdir)

    setup_logger(args.outdir, args.label)
    logger.info("Arguments: %s", vars(args))

    model_fine_tuned = UNET2D(in_channels=2, out_channels=2)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model_fine_tuned.to(device)

    data = np.load(args.data)

    weights = torch.load(args.model, map_location=device, weights_only=True)
    model_fine_tuned.load_state_dict(weights['state_dict'])
    model_fine_tuned.eval()

    scaler = pickle.load(open("../../deepextractor/data/scaler_bilby.pkl", 'rb'))

    detectors = [key for key in data.keys() if key != 'null_stream']

   


    if len(detectors)==3:
        logger.info("Triangle found. Computing the null stream SNR")

        dex_snr = {}
        for i, det in enumerate(detectors):
            input_timeseries = np.asarray(data[det])
            dex_snr[det], dex_snr['time_stamps'] = process_segments(input_timeseries, model_fine_tuned, scaler, 
                                        args.delta_t, args.sampling_frequency, device)

        
        dex_snr['network_snr']  = np.sqrt(sum(dex_snr[det]**2 for det in detectors))
        null_stream_snr, _ = process_segments(np.asarray(data['null_stream']), model_fine_tuned, scaler, 
                                                          args.delta_t, args.sampling_frequency, device)
        dex_snr['null_stream'] = np.sqrt(3)*(null_stream_snr)
    



        dex_snr['combined_statistic'] = dex_snr['network_snr'] - dex_snr['null_stream']

    elif len(detectors)==2:
        dex_snr = {}
        logger.info("L-shape found. Computing mismatch integral")

        D0 = detectors[0]
        D1 = detectors[1]
        dex_snr[D0], dex_snr[D1], dex_snr["mismatch_overlap"], dex_snr['time_stamps'] = joint_processing(np.asarray(data[D0]), np.asarray(data[D1]), model_fine_tuned, scaler, 
                                                          args.delta_t, args.sampling_frequency, device, args.minimum_frequency)
        
        #dex_snr["mismatch_overlap"] = np.ones(len(dex_snr["network_snr"]))

        dex_snr['network_snr'] = np.sqrt(sum(dex_snr[det]**2 for det in detectors))

        dex_snr['combined_statistic'] = dex_snr['network_snr'] * dex_snr["mismatch_overlap"]

    np.savez(f"{args.outdir}/dex_snr.npz", **dex_snr)


if __name__ == "__main__":
    main()