from glob import glob
from pycbc.filter.matchedfilter import match
from pycbc.frame import read_frame, write_frame
from pycbc.types import TimeSeries
from tqdm import tqdm
import logging
import os
import argparse
import pickle
# DeepExtractor is based on the U-Net architecture
from models.models import UNET2D
import numpy as np
import torch

logger = logging.getLogger("reconstruct")
DEBUG = False


def setup_logger(outdir, label):
    logger.setLevel(logging.INFO)
    fh = logging.FileHandler(f"{outdir}/{label}_reconstruct.log")
    fh.setFormatter(logging.Formatter(
        "%(asctime)s - %(levelname)s - %(message)s"))
    logger.addHandler(fh)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Reconstruct SNR using DeepExtractor")
    parser.add_argument("--frame-directory", type=str,
                        help="Location of the gwf frame files generated by generate_frames.py script")
    parser.add_argument('--detector-network', type=str, default='ETT',
                        help='Switch of ET2L for a different design')
    parser.add_argument(
        "--model", type=str,
        default=(
            "../weights/checkpoints_1024/UNET2D_glitch_target_checkpoints/"
            "checkpoint_best_bilby_noise_transfer_learn.pth.tar"
        ))
    parser.add_argument("--outdir", type=str, default="deleteme")
    parser.add_argument("--label", type=str, default="deleteme")
    parser.add_argument("--sampling-frequency", type=float, default=4096)
    parser.add_argument("--minimum-frequency", type=float, default=20.)
    parser.add_argument("--delta-t", type=float, default=2,
                        help="Sliding duration for the DE window")

    return parser.parse_args()


def compute_snr(reconstruced_signal, data):
    sigma_squared = np.sum(reconstruced_signal * data)
    return np.sqrt(abs(sigma_squared))


def process_segments(input_frame, model, scaler, delta_t, sampling_frequency,
                     device, minimum_frequency, outdir, label, det, segment_size=8192):
    """
    Divide data into segments, reconstruct signal for each, and return SNR values.

    Args:
        data_array: pycbc timeseries
        model: Fine-tuned model for noise prediction
        scaler: Scaler for normalizing/denormalizing the data
        device: Device to run the model on ('cuda' or 'cpu')
        segment_size: Size of each segment (default: 8192)

    Returns:
        snr_values: List of SNR values for each segment
    """
    whitened_frame = np.array(input_frame.whiten(
        segment_duration=16, max_filter_duration=2, low_frequency_cutoff=minimum_frequency))
    # This is to make sure the whitned strain has a standard deviation of 1 unit.
    whitened_frame /= np.std(whitened_frame)

    np.arange(len(whitened_frame)) / sampling_frequency

    if DEBUG:
        x = np.arange(-5, 5, 0.1)
        gaussian = np.exp(-1 * np.power(x, 2) / 2) / np.sqrt(2 * np.pi)
        import matplotlib.pyplot as plt
        fig, ax = plt.subplots()
        ax.hist(whitened_frame, density=1, histtype='step', bins=40)
        ax.plot(x, gaussian, color='black')
        fig.savefig(f"{outdir}/{label}_{det}_whitened.pdf")

    n_samples = len(whitened_frame)

    snr_values = []
    step_size_in_idx = int(delta_t * sampling_frequency)
    bins = np.arange(0, n_samples - step_size_in_idx,
                     step_size_in_idx, dtype=int)
    time_stamps = bins / sampling_frequency
    for ii in tqdm(range(len(bins))):
        start_idx = bins[ii]
        segment = whitened_frame[start_idx:(start_idx + segment_size)]
        reconstructed = reconstruct_signal(segment, model, scaler, device)
        snr = compute_snr(reconstructed, segment)
        snr_values.append(snr)

    epoch = float(input_frame.start_time) + time_stamps[0]
    return TimeSeries(np.array(snr_values), delta_t=delta_t, epoch=epoch)


def joint_processing(frame_1, frame_2, model, scaler, delta_t, sampling_frequency,
                     device, minimum_frequency, segment_size=8192):
    n_samples = len(frame_1)
    bins = np.arange(0, n_samples - segment_size + 1,
                     int(delta_t * sampling_frequency), dtype=int)
    time_stamps = bins[:-1] / sampling_frequency

    whitened_frame_1 = np.array(frame_1.whiten())
    whitened_frame_2 = np.array(frame_2.whiten())

    snr_values_1, snr_values_2, match_values = [], [], []
    for ii in tqdm(range(len(bins) - 1)):
        seg_1 = whitened_frame_1[bins[ii]:bins[ii + 1]]
        seg_2 = whitened_frame_2[bins[ii]:bins[ii + 1]]
        rec_1 = reconstruct_signal(seg_1, model, scaler, device)
        rec_2 = reconstruct_signal(seg_2, model, scaler, device)

        snr_values_1.append(compute_snr(rec_1, seg_1))
        snr_values_2.append(compute_snr(rec_2, seg_2))
        match_values.append(compute_overlap(
            rec_1, rec_2, sampling_frequency, minimum_frequency))

    epoch = float(frame_1.start_time) + time_stamps[0]
    snr_ts_1 = TimeSeries(np.array(snr_values_1),
                          delta_t=delta_t, epoch=epoch)
    snr_ts_2 = TimeSeries(np.array(snr_values_2),
                          delta_t=delta_t, epoch=epoch)
    match_ts = TimeSeries(np.array(match_values),
                          delta_t=delta_t, epoch=epoch)
    return snr_ts_1, snr_ts_2, match_ts


def reconstruct_signal(input_series, model, scaler, device):
    """
    Reconstruct a glitch signal by subtracting predicted noise from the input.

    Args:
        input_series: Input time series (numpy array)
        model: Fine-tuned model for noise prediction
        scaler: Scaler for normalizing/denormalizing the data
        device: Device to run the model on ('cuda' or 'cpu')

    Returns:
        g_hat: Reconstructed glitch signal (numpy array)
    """
    # STFT parameters
    n_fft = 256
    win_length = n_fft // 2
    hop_length = win_length // 2
    window = torch.hann_window(win_length)

    # Scale the input
    input_scaled = scaler.transform(
        input_series.reshape(-1, 1)).reshape(input_series.shape)

    # Convert to tensor and compute STFT
    signal_tensor = torch.tensor(input_scaled, dtype=torch.float32)
    stft_result = torch.stft(
        signal_tensor,
        n_fft=n_fft,
        hop_length=hop_length,
        win_length=win_length,
        window=window,
        return_complex=True
    )

    # Extract magnitude and phase
    magnitude = torch.abs(stft_result)
    phase = torch.angle(stft_result)

    # Stack and prepare for model
    stft_mag_phase = torch.stack([magnitude, phase], dim=0)
    stft_mag_phase = stft_mag_phase.unsqueeze(0)
    h_stft = stft_mag_phase.float().to(device)

    # Model prediction
    with torch.no_grad():
        n_hat_stft = model(h_stft)

    n_hat_stft = n_hat_stft.cpu()

    # Separate magnitude and phase from prediction
    magnitude_pred = n_hat_stft[:, 0, :, :]
    phase_pred = n_hat_stft[:, 1, :, :]

    # Convert back to complex STFT
    real_part = magnitude_pred * torch.cos(phase_pred)
    imag_part = magnitude_pred * torch.sin(phase_pred)
    stft_complex = torch.complex(real_part, imag_part)

    # Perform iSTFT to get time series
    n_hat_scaled = torch.istft(
        stft_complex,
        n_fft=n_fft,
        hop_length=hop_length,
        win_length=win_length,
        window=window,
    )
    n_hat_scaled = n_hat_scaled.numpy().squeeze()

    # Scale back the inverse transformed data
    n_hat = scaler.inverse_transform(
        n_hat_scaled.reshape(-1, n_hat_scaled.shape[-1])
    ).reshape(n_hat_scaled.shape)

    # Reconstruct the glitch by subtracting the predicted noise
    s_hat = input_series - n_hat

    return s_hat


def compute_overlap(ts1, ts2, sampling_frequency, minimum_frequency):
    ts1 = TimeSeries(ts1, delta_t=1 / sampling_frequency, epoch=0.)
    ts2 = TimeSeries(ts2, delta_t=1 / sampling_frequency, epoch=0)
    # PSD?
    overlap, _ = match(ts1, ts2, low_frequency_cutoff=minimum_frequency,
                       high_frequency_cutoff=sampling_frequency * 0.5)
    return overlap


def find_frames(frame_location, detector_network):
    if detector_network == "ETT":
        E1 = glob(f"{frame_location}/*E1*signal_and_noise*gwf")[0]
        E2 = glob(f"{frame_location}/*E2*signal_and_noise*gwf")[0]
        E3 = glob(f"{frame_location}/*E3*signal_and_noise*gwf")[0]
        null_stream = glob(f"{frame_location}/*null_stream*gwf")[0]

        frame_dict = {
            'E1': read_frame(E1, 'E1:STRAIN'),
            'E2': read_frame(E2, 'E2:STRAIN'),
            'E3': read_frame(E3, 'E3:STRAIN'),
            'null_stream': read_frame(null_stream, 'NULL:STRAIN'),
        }

    elif detector_network == "ET2L":

        ETLim = glob(f"{frame_location}/*ETLim*signal_and_noise*gwf")[0]
        ETSar = glob(f"{frame_location}/*ETSar*signal_and_noise*gwf")[0]

        frame_dict = {
            'ETLim': read_frame(ETLim, 'ETLim:STRAIN'),
            'ETSar': read_frame(ETSar, 'ETSar:STRAIN'),
        }

    return frame_dict


def main():
    """
    This function filters the data generated by generate_frames.py script.
    It filters the data using the DE model.
    It saves the SNR estimated by the DE model in the form of numpy arrays.
    """
    args = parse_args()
    if not os.path.isdir(args.outdir):
        os.mkdir(args.outdir)

    setup_logger(args.outdir, args.label)
    logger.info("Arguments: %s", vars(args))

    model_fine_tuned = UNET2D(in_channels=2, out_channels=2)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model_fine_tuned.to(device)

    frame_dictionary = find_frames(args.frame_directory, args.detector_network)
    detectors = list(frame_dictionary.keys())

    for det, path in frame_dictionary.items():
        logger.info("Reading frame: %s -> %s", det, path)

    weights = torch.load(args.model, map_location=device, weights_only=True)
    model_fine_tuned.load_state_dict(weights['state_dict'])
    model_fine_tuned.eval()

    scaler = pickle.load(
        open("../scaler/scaler_bilby.pkl", 'rb'))

    if args.detector_network == "ETT":

        logger.info("Triangle found. Computing the null stream SNR")

        dex_snr = {}
        for det in detectors:
            dex_snr[det] = process_segments(
                frame_dictionary[det], model_fine_tuned, scaler,
                args.delta_t, args.sampling_frequency, device, args.minimum_frequency,
                args.outdir, args.label, det)

        detectors.remove('null_stream')
        dex_snr['network_snr'] = sum(
            dex_snr[det] ** 2 for det in detectors) ** 0.5

        dex_snr['combined_statistic'] = (
            dex_snr['network_snr'] - dex_snr['null_stream'] * np.sqrt(3))

    elif args.detector_network == "ET2L":
        dex_snr = {}
        logger.info("L-shape found. Computing mismatch integral")

        (dex_snr['ETSar'], dex_snr['ETLim'],
         dex_snr["mismatch_overlap"], dex_snr['time_stamps']) = joint_processing(
            frame_dictionary['ETSar'], frame_dictionary['ETLim'],
            model_fine_tuned, scaler, args.delta_t, args.sampling_frequency,
            device, args.minimum_frequency)

        dex_snr['network_snr'] = np.sqrt(
            sum(dex_snr[det] ** 2 for det in detectors))

        dex_snr['combined_statistic'] = (
            dex_snr['network_snr'] * dex_snr["mismatch_overlap"])

    for key, ts in dex_snr.items():
        write_frame(f"{args.outdir}/{args.label}_dex_snr_{key}.gwf",
                    f"DEX:{key.upper()}", ts)


if __name__ == "__main__":
    main()
