name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Build paper
        uses: actions/checkout@v6
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: paper/unmodelled_search.tex
          args: -pdf -pdflatex="pdflatex -interaction=nonstopmode"
      - name: Upload PDF file
        uses: actions/upload-artifact@v6
        with:
          name: PDF
          path: paper/unmodelled_search.pdf